#ifndef MB_TRANSPORT_WS_WS_H_INCLUDED
#define MB_TRANSPORT_WS_WS_H_INCLUDED

#define MB_WS_FIN_BIT       0x80
#define MB_WS_OPCODE_TEXT    0x01
#define MB_WS_OPCODE_BINARY  0x02
#define MB_WS_OPCODE_CLOSE   0x08
#define MB_WS_OPCODE_PING    0x09
#define MB_WS_OPCODE_PONG    0x0A
#define MB_WS_MASK_BIT       0x80
#define MB_WS_MAX_HDR_SIZE   14

#define MB_WS_MAGIC "258EAFA5-E914-47DA-95CA-5AB5F8A5B5E3"

#endif
